### ISSUE TITLE
Информация за контролни/изпит

### ISSUE THREAD

**Issue by cupperus** [iproduct/course-node-express-react#2]
Привет,
Можете ли да публикувате информация за датите за предстоящите контролни/изпит и защити на проекти?

Лек ден!

**Comment by LeadVocals** [comment]
Има ли tutorials , лекции и други, къде качваме проекти и домашни? Тук виждам само сорсовете... Поздрави!

**Comment by AleksandarAleksandrov** [comment]
Подкрепям първият колега за въпросите.

**Comment by iproduct** [comment]
Презентациите са в Wiki-то на курса. Както и важните дати (датата за изпит остава да уточним на занятия).
Решенията на домашните искам да ги погледнем на упражнения за да ги оценя. Първото домашно е достъпно от секция Homeworks в Wiki-to. 

Ако имате други въпроси - моля пишете ми по е-мейл (адреса е най-отгоре в Wiki-to :). Нека да ползваме GitHub Issues по предназначение :)
